apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: lws.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: LeaderWorkerSet is the Schema for the leaderworkersets API
      displayName: Leader Worker Set
      kind: LeaderWorkerSet
      name: leaderworkersets.leaderworkerset.x-k8s.io
      version: v1
  description: 'LeaderWorkerSet: An API for deploying a group of pods as a unit of
    replication'
  displayName: lws
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - inferencing
  links:
  - name: Lws
    url: https://lws.domain
  maintainers:
  - email: kehannon@redhat.com
    name: kevinhannon
  maturity: alpha
  minKubeVersion: 1.32.0
  provider:
    name: openshift
  version: 0.0.0
